name: dp-apache-airflow
channels:
- default
- conda-forge
dependencies:
- python=3.8
- airflow
- apache-airflow-providers-amazon
- apache-airflow-providers-postgres=2.0.0
- black
- flake8
- pre_commit
